config/routes.rb
Workmachine::Application.routes.draw do

  resources :clients

  devise_for :users
  resources :invites

  resources :users

  resources :projects do
    resources :notes, shallow: true
  end

  root 'home#index'

end

app/models/invite.rb
class Invite < ActiveRecord::Base

  validates :email, 
    presence: true, 
    length: { maximum: 250, too_long: "must have at most %{count} characters" },
    uniqueness: true,
    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :set_invite, only: [:show, :edit, :update, :destroy]

  # GET /invites
  # GET /invites.json
  def index
    @invites = Invite.all
  end

  # GET /invites/1
  # GET /invites/1.json
  def show
  end

  # GET /invites/new
  def new
    @invite = Invite.new
  end

  # GET /invites/1/edit
  def edit
  end

  # POST /invites
  # POST /invites.json
  def create
    @invite = Invite.new(invite_params)

    respond_to do |format|
      if @invite.save
        format.html { redirect_to @invite, notice: 'Invite was successfully created.' }
        format.json { render action: 'show', status: :created, location: @invite }
      else
        format.html { render action: 'new' }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invites/1
  # PATCH/PUT /invites/1.json
  def update
    respond_to do |format|
      if @invite.update(invite_params)
        format.html { redirect_to @invite, notice: 'Invite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invites/1
  # DELETE /invites/1.json
  def destroy
    @invite.destroy
    respond_to do |format|
      format.html { redirect_to invites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invite
      @invite = Invite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invite_params
      params.require(:invite).permit(:email)
    end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_form.html.erb
<%= form_for(@invite) do |f| %>
  <% if @invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invite.errors.count, "error") %> prohibited this invite from being saved:</h2>

      <ul>
      <% @invite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit :class => "button" %>
  </div>
<% end %>

app/views/invites/edit.html.erb
<h1>Editing invite</h1>

<%= render 'form' %>

<%= link_to 'Show', @invite %> |
<%= link_to 'Back', invites_path %>

app/views/invites/index.html.erb
<h1>Listing invites</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @invites.each do |invite| %>
      <tr>
        <td><%= invite.email %></td>
        <td><%= link_to 'Show', invite %></td>
        <td><%= link_to 'Edit', edit_invite_path(invite) %></td>
        <td><%= link_to 'Destroy', invite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invite', new_invite_path %>

app/views/invites/new.html.erb
<h1>New invite</h1>

<%= render 'form' %>

<%= link_to 'Back', invites_path %>

app/views/invites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @invite.email %>
</p>

<%= link_to 'Edit', edit_invite_path(@invite) %> |
<%= link_to 'Back', invites_path %>