config/routes.rb
Workmachine::Application.routes.draw do

  resources :clients

  devise_for :users
  resources :invites

  resources :users

  resources :projects do
    resources :notes, shallow: true
  end

  root 'home#index'

end

app/models/note.rb
class Note < ActiveRecord::Base

  belongs_to :project

  validates :name, 
    presence: true, 
    length: { maximum: 500, too_long: "must have at most %{count} characters" }
  validates :project_id, 
    presence: true, 
    numericality: { only_integer: true }
  validates :user_id, 
    allow_nil: true,
    numericality: { only_integer: true }
  validate :due_must_make_sense

  private
    def due_must_make_sense
      if due < start
        errors.add(:due, 'Due date cannot be before start date')
      end
    end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_project
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = @project.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = @project.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to project_notes_path(@project), notice: 'Note was successfully created.' }
        format.json { render action: 'show', status: :created, location: @note }
      else
        format.html { render action: 'new' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to project_notes_path(@project), notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to project_notes_url }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = @project.notes.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:project_id, :user_id, :name, :start, :due)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for([@project, @note]) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.date_select :start %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.date_select :due %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', [@project, @note] %> |
<%= link_to 'Back', project_notes_path(@project) %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <thead>
    <tr>
      <th>Project ID</th>
      <th>User</th>
      <th>Name</th>
      <th>Start</th>
      <th>Due</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.project_id %></td>
        <td><%= note.user_id %></td>
        <td><%= note.name %></td>
        <td><%= note.start %></td>
        <td><%= note.due %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_project_note_path(@project) %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', project_notes_path(@project) %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @note.project_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @note.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @note.name %>
</p>

<p>
  <strong>Start:</strong>
  <%= @note.start %>
</p>

<p>
  <strong>Due:</strong>
  <%= @note.due %>
</p>

<%= link_to 'Edit', edit_project_note_path(@project, @note) %> |
<%= link_to 'Back', project_notes_path(@project) %>